### PR TITLE
Misc error checking

### LINKED ISSUE #68: Incorrectly finds QR codes and returns malformed data
Several issues have come with with the library incorrectly locating QR codes where there aren't any, returning malformed data (often manifesting as Chinese characters). 

This is an central issue to track these issue on. I've been able to reproduce the error with this image 
malformed. 

We'll use this image to try to catch the issue (thinking we're not correctly detecting error correction levels).

### PR DESCRIPTION
**Pull request by cozmo**
Fixes #68 and #53. 

We were seeing 2 intermittent errors. 
1. Sometimes getting `Uncaught RangeError: Invalid typed array length: Infinity` in extract. This was caused by the moduleSize calculation in locate returning 0, so returning a QR of infinite size (`edgeLength/moduleSize`). We now explicitly check for this case and bail out of locator. This fixes part of #53.
2. Sometimes we'd return malformed data, either manifesting as random unicode characters or an empty byte array.  Both of these cases were caused when we couldn't pull off enough codewords from the matrix. We now explicitly check that we pull off at least the number of codewords as we expect. 

No changes to the end to end tests which is good, and have added explicit test cases for these failure cases.

### CODE REVIEW

File: src/locator/index.ts [hunk 1]
```diff
@@ -360,7 +364,15 @@ export function locate(matrix: BitMatrix): QRLocation {
 
   // Now that we've found the three finder patterns we can determine the blockSize and the size of the QR code.
   // We'll use these to help find the alignment pattern but also later when we do the extraction.
-  const { dimension, moduleSize } = computeDimension(topLeft, topRight, bottomLeft, matrix);
+  let dimension: number;
+  let moduleSize: number;
+  try {
+    const computedDimension = computeDimension(topLeft, topRight, bottomLeft, matrix);
```
Comment (jefff) [inline src/locator/index.ts]: nit: You could use destructuring here.

`({ dimension, moduleSize } = computeDimension(topLeft, topRight, bottomLeft, matrix));`

File: src/locator/index.ts [hunk 2]
```diff
@@ -62,6 +62,10 @@ function computeDimension(topLeft: Point, topRight: Point, bottomLeft: Point, ma
     sum(countBlackWhiteRun(topRight, topLeft, matrix, 5)) / 7
   ) / 4;
 
+  if (moduleSize === 0) {
```
Comment (jefff) [inline src/locator/index.ts]: Unless 0 is a magic number being returned by something, it'd probably be better to switch this to something like `if (moduleSize < 1) {` or whatever the smallest reasonable module size is to avoid float rounding issues.

File: src/locator/index.ts (hunk 1 above)
Comment (cozmo) [reply src/locator/index.ts]: Ah I was trying to do that but didn't have the syntax right. Added in a8ceef6.

File: src/locator/index.ts (hunk 2 above)
Comment (cozmo) [reply src/locator/index.ts]: So at least with the test case this was triggering because `countBlackWhiteRun` was returning `[0,0,-1,0,0]` which basically means the finder patterns were too small to extract distances from. We could try throwing deeper in the stack but it felt reasonable to just check for an explicit 0 here. Thoughts?
